#!/bin/bash
####  PBS preamble

#PBS -N fp.5c.sp.array
#PBS -l nodes=1:ppn=1,mem=1gb,walltime=00:02:00
#PBS -t 1-10

#PBS -M daiweiz@umich.edu
#PBS -j oe
#PBS -o logs/
#PBS -e logs/
#PBS -m abe
#PBS -V
#PBS -A leeshawn_fluxod
#PBS -q fluxod
#PBS -l qos=flux
####  End PBS preamble


set -e
# Print system info
#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi
#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi
# Print job and array ids
echo $PBS_JOBID
echo $PBS_ARRAYID
jobid="${PBS_JOBID:0:8}"
# module load R mkl/11.3.3 gcc/5.4.0 armadillo plink

#  Put your job commands here:
n_chunks=10
pref_ref=../data/kgn/kgn_bial_orphans_snps_ukb_snpscap_ukb
pref_stu=../data/ukb/ukb_snpscap_kgn_bial_orphans_5c
i=$PBS_ARRAYID
pref_stu=`bash split_bed_indivs.sh ${pref_stu} ${n_chunks} ${i} | tail -n 1`

method=oadp
# j=$PBS_ARRAYID
# let "i = j % ${n_chunks}"
# let "method = j / ${n_chunks}"
date
python -c "import frugalpca as fp; fp.run_pca('${pref_ref}', '${pref_stu}', '${method}')"
date

