#!/bin/bash
####  PBS preamble

#PBS -N fpt.5c
#PBS -l nodes=1:ppn=1,mem=4,walltime=01:00:00
# use this for array: #PBS -t 0-4

#PBS -M daiweiz@umich.edu
#PBS -j oe
#PBS -o log/
#PBS -e log/
#PBS -m abe
#PBS -V
#PBS -A leeshawn_fluxod
#PBS -q fluxod
#PBS -l qos=flux
####  End PBS preamble

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

# Print job and array ids
echo $PBS_JOBID
echo $PBS_ARRAYID
id="${PBS_JOBID:0:8}"

#  Put your job commands here:

date
# module load R mkl/11.3.3 gcc/5.4.0 armadillo plink
python -c "import frugalpca_tests as fpt; fpt.test_pca_ggsim()"
date
