#!/bin/bash
####  PBS preamble

#PBS -N fp.EUR.homogen.sp
#PBS -l nodes=1:ppn=1,mem=4gb,walltime=00:30:00
#PBS -t 0-99

#PBS -M daiweiz@umich.edu
#PBS -j oe
#PBS -o logs/
#PBS -e logs/
#PBS -m abe
#PBS -V
#PBS -A leeshawn_fluxod
#PBS -q fluxod
#PBS -l qos=flux
####  End PBS preamble

set -e -o pipefail

# Print system info
#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi
#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi
# Print job and array ids
echo $PBS_JOBID
echo $PBS_ARRAYID
jobid="${PBS_JOBID:0:8}"
# module load R mkl/11.3.3 gcc/5.4.0 armadillo plink

# #  Put your job commands here:
# method=ap
# pref_ref=../data/kgn/kgn_bial_orphans_snps_ukb_snpscap_ukb_EUR
# pref_stu=../data/ukb/ukb_snpscap_kgn_bial_orphans_pred_EUR
# n_chunks=100
# i=$PBS_ARRAYID
# date
# python -c "import frugalpca_tests as fpt; fpt.test_pca_array('${pref_ref}', '${pref_stu}', '${method}', ${n_chunks}, ${i})"
# date

#  Put your job commands here:
# python -c "import frugalpca_tests as fpt; fpt.test_pca_5c()"
# python -c "import frugalpca_tests as fpt; fpt.test_pca_5c_EUR()"
# python -c "import frugalpca_tests as fpt; fpt.test_pca_ggsim()"

#  Put your job commands here:
i=$PBS_ARRAYID
method=sp
pref_ref=../data/kgn/kgn_bial_orphans_snps_ukb_snpscap_ukb_EUR_merge_ukb_EUR_pure_homogen
pref_stu=../data/ukb/ukb_snpscap_kgn_bial_orphans_pred_EUR_nchunks100/ukb_snpscap_kgn_bial_orphans_pred_EUR_heterogen_nchunks100/ukb_snpscap_kgn_bial_orphans_pred_EUR_heterogen_nchunks100
pref_stu=${pref_stu}_`printf "%04d" ${i}`
# pref_stu=../data/ukb/ukb_snpscap_kgn_bial_orphans_pred_EUR_impure_nchunks100/ukb_snpscap_kgn_bial_orphans_pred_EUR_impure_nchunks100_`printf "%04d" ${i}`
python -c "import frugalpca as fp; fp.run_pca('${pref_ref}', '${pref_stu}', '${method}')"

# #  Put your job commands here:
# for i in `seq 0 99`; do
#     id=`printf "%04d" ${i}`
#     plink --bfile ../data/ukb/ukb_snpscap_kgn_bial_orphans_pred_EUR_nchunks100/ukb_snpscap_kgn_bial_orphans_pred_EUR_nchunks100_${id} --keep-allele-order --remove ../data/ukb/ukb_snpscap_kgn_bial_orphans_pred_EUR_nchunks100/ukb_EUR_pure.popu --out ../data/ukb/ukb_snpscap_kgn_bial_orphans_pred_EUR_nchunks100/ukb_snpscap_kgn_bial_orphans_pred_EUR_impure_nchunks100_${id} --make-bed
# done
