#!/bin/bash
####  PBS preamble

#PBS -N kgn_train_test
# Change the number of cores (ppn=1), amount of memory, and walltime:
#PBS -l nodes=1:ppn=1,mem=32gb,walltime=1:00:00:00
# use this for array: #PBS -t 0-4

#PBS -M daiweiz@umich.edu
#PBS -j oe
#PBS -m abe
#PBS -V
#PBS -A leeshawn_fluxod
#PBS -q fluxod
#PBS -l qos=flux
####  End PBS preamble

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

# Print job and array ids
echo $PBS_JOBID
echo $PBS_ARRAYID

id="${PBS_JOBID:0:8}"

#  Put your job commands here:

date
bash chain.sh 0 rand kgn kgn_chr_all_keep_orphans_snp_hgdp_train kgn kgn_chr_all_keep_orphans_snp_hgdp_test ${id}
date
