#!/bin/bash
####  PBS preamble

#PBS -N trace.nChg
# Change the number of cores (ppn=1), amount of memory, and walltime:
#PBS -l nodes=1:ppn=1,mem=16gb,walltime=0:02:00:00
#PBS -t 0-4

#PBS -M daiweiz@umich.edu
#PBS -j oe
#PBS -o log/
#PBS -e log/
#PBS -m abe
#PBS -V
#PBS -A leeshawn_fluxod
#PBS -q fluxod
#PBS -l qos=flux
####  End PBS preamble

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

# Print job and array ids
echo $PBS_JOBID
echo $PBS_ARRAYID

#  Put your job commands here:
i=$PBS_ARRAYID
let "n = 1000 + 500 * i"
id="${PBS_JOBID:0:8}"
pref=ggsim${n}

date
# bash chain.sh 1 ori ${pref} 100000 $n 200 2 1 100
# trace -s ../data/ukb/ukb_snpscap_kgn_bial_orphans_5c_pred_EUR.geno -g ../data/kgn/kgn_bial_orphans_snps_ukb_snpscap_ukb_EUR.geno -o ../data/ukb/ukb_snpscap_kgn_bial_orphans_5c_pred_EUR -k 4 -K 20
trace -s ../data/${pref}/${pref}_100000_200_2_1_100_1.geno -g ../data/${pref}/${pref}_100000_${n}_2_1_100_0.geno -o ../data/${pref}/${pref}_100000_200_2_1_100_1_sturef_${pref}_100000_${n}_2_1_100_0 -k 4 -K 20
date

