#!/bin/bash
####  PBS preamble

#PBS -N trace.ggsim
# Change the number of cores (ppn=1), amount of memory, and walltime:
#PBS -l nodes=1:ppn=1,mem=4gb,walltime=03:00:00
#PBS -t 0-4

#### #PBS -M daiweiz@umich.edu
#PBS -j oe
#PBS -m abe
#PBS -o logs/
#PBS -e logs/
#PBS -V
#PBS -A leeshawn_fluxod
#PBS -q fluxod
#PBS -l qos=flux
####  End PBS preamble

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

# Print job and array ids
echo $PBS_JOBID
echo $PBS_ARRAYID
id="${PBS_JOBID:0:8}"

#  Put your job commands here:
trace=/home/daiweiz/laser/trace

date
i=$PBS_ARRAYID
let 'n=1000+i*500'
timestamp=`date +%s`
geno_file=/scratch/leeshawn_fluxod/daiweiz/data/ggsim${n}/ggsim${n}_100000_${n}_2_1_100_0.geno
study_file=/scratch/leeshawn_fluxod/daiweiz/data/ggsim${n}/ggsim${n}_100000_200_2_1_100_1.geno
pref_out=/scratch/leeshawn_fluxod/daiweiz/data/ggsim${n}/ggsim${n}_100000_${n}_200_2_1_100_${timestamp}
${trace} \
        -g ${geno_file} \
        -s ${study_file} \
        -o ${pref_out} \
        -k 2 \
        -K 20
date

# geno_file=/scratch/leeshawn_fluxod/daiweiz/data/kgn/kgn_bial_orphans_snps_ukb_snpscap_ukb.geno
# study_file=/scratch/leeshawn_fluxod/daiweiz/data/ukb/ukb_snpscap_kgn_bial_orphans_5c.geno
# pref_out=/scratch/leeshawn_fluxod/daiweiz/data/ukb/ukb_snpscap_kgn_bial_orphans_5c_sturef_kgn_bial_orphans_snpscap_ukb

# geno_file=/scratch/leeshawn_fluxod/daiweiz/data/kgn/kgn_bial_orphans_snps_ukb_snpscap_ukb_EUR.geno
# study_file=/scratch/leeshawn_fluxod/daiweiz/data/ukb/ukb_snpscap_kgn_bial_orphans_pred_EUR_5c.geno
# pref_out=/scratch/leeshawn_fluxod/daiweiz/data/ukb/ukb_snpscap_kgn_bial_orphans_pred_EUR_5c_sturef_kgn_bial_orphans_snps_ukb_snpscap_ukb_EUR
# 
# trace \
#         -g ${geno_file} \
#         -s ${study_file} \
#         -o ${pref_out} \
#         -k 4 \
#         -K 20
# date
